# Generated by Django 4.1.7 on 2023-03-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptrade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenu',
            options={'verbose_name': 'Главное меню', 'verbose_name_plural': 'Главное меню'},
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='url_slug',
            field=models.SlugField(unique=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='url_slug',
            field=models.SlugField(unique=True, verbose_name='Url'),
        ),
    ]
