# Generated by Django 4.1.7 on 2023-03-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_category_article_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(blank=True, default='2023-03-20 16:40:32', verbose_name='Дата публикации'),
        ),
    ]
