# Generated by Django 4.1.7 on 2023-03-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.SlugField(max_length=20)),
                ('password', models.SlugField(max_length=16)),
            ],
            options={
                'verbose_name': 'Данные',
            },
        ),
    ]
