# Generated by Django 4.1.7 on 2023-03-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auth',
            options={'verbose_name': 'Данные', 'verbose_name_plural': 'Данные'},
        ),
        migrations.AlterField(
            model_name='auth',
            name='login',
            field=models.SlugField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='auth',
            name='password',
            field=models.SlugField(max_length=16, unique=True),
        ),
    ]
