# Generated by Django 4.1.7 on 2023-03-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_alter_auth_options_alter_auth_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='password',
            field=models.SlugField(max_length=16),
        ),
    ]
